version: '3.3'

services:
  app:
    build: .
    depends_on:
      -  db
    #ports:
    #  - "8080:8080"
    volumes:
      - ./app:/app
      - ./img:/img
    restart: always
  db:
    image: mongo
    restart: always
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - ./db:/data/db
  imaginary:
    image: h2non/imaginary:latest
    volumes:
    - ./img:/img
    environment:
      PORT: 9000
    command: -disable-endpoints form,health -mount /img  -enable-url-source -allowed-origins http://localhost
    #ports:
    # - "9000:9000"
  nginx:
    image: nginx:latest
    ports:
      - '9090:80'
    restart: always
    volumes: 
      - ./templates:/etc/nginx/templates
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./auth.txt:/etc/nginx/htpasswd/auth.txt
